# Generated by Django 5.2.7 on 2026-08-19 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDefinedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('website', 'Website / App Launch'), ('marketing', 'Marketing'), ('design', 'Design'), ('development', 'Development'), ('operations', 'Operations'), ('finance', 'Finance'), ('hr', 'HR / Hiring'), ('general', 'General')], default='general', max_length=30)),
                ('suggested_priority', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='moderate', max_length=10)),
                ('icon', models.CharField(default='fas fa-tasks', max_length=50)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('not-started', 'To Do'), ('in-progress', 'In Progress'), ('completed', 'Done'), ('on-hold', 'On Hold'), ('canceled', 'Canceled')], default='not-started', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=10)),
                ('notify_task_reminders', models.BooleanField(default=True)),
                ('notify_due_date_alerts', models.BooleanField(default=True)),
                ('notify_app_updates', models.BooleanField(default=False)),
                ('default_task_priority', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='moderate', max_length=10)),
                ('default_task_status', models.CharField(choices=[('backlog', 'Backlog'), ('not-started', 'To Do'), ('in-progress', 'In Progress'), ('completed', 'Done'), ('on-hold', 'On Hold'), ('canceled', 'Canceled')], default='not-started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
