# Generated by Django 5.2.7 on 2026-08-22 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_checklist_taskcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedtask',
            name='category',
            field=models.CharField(choices=[('website', 'Website / App Launch'), ('marketing', 'Marketing'), ('design', 'Design'), ('development', 'Development'), ('operations', 'Operations'), ('finance', 'Finance'), ('hr', 'HR / Hiring'), ('general', 'General')], db_index=True, default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], db_index=True, default='moderate', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('not-started', 'To Do'), ('in-progress', 'In Progress'), ('completed', 'Done'), ('on-hold', 'On Hold'), ('canceled', 'Canceled')], db_index=True, default='not-started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='category_user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='task_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'due_date'], name='task_user_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'priority'], name='task_user_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'category'], name='task_user_category_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='comment_task_created_idx'),
        ),
    ]
