# Generated by Django 5.2.12 on 2026-08-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checklist_title',
            field=models.CharField(blank=True, default='Checklist', max_length=100),
        ),
    ]
