# Generated by Django 5.2.12 on 2026-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_task_checklist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='board_template',
            field=models.CharField(choices=[('smart', 'Smart Work Management (4 Lists)'), ('super', 'Super Work Management (6 Lists)')], default='smart', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='column_names',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
