# Generated by Django 5.2.12 on 2026-08-24 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_category_board_template_category_column_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_comment', 'Task Comment Added'), ('task_due_soon', 'Task Due Soon'), ('task_completed', 'Task Completed'), ('project_shared', 'Project Shared'), ('welcome', 'Welcome to TaskFlixx'), ('system', 'System Notification')], db_index=True, default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('html_content', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='todo_notifi_status_b68ba4_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='todo_notifi_user_id_dbe554_idx')],
            },
        ),
    ]
